### ISSUE TITLE
My google phishing website takes a while to load 

### ISSUE THREAD

**Issue by peaillaud** [hash3liZer/phishlets#20] opened 2020-04-16 13:09 UTC
Hi,
I am using your Google phishlet. It works pefectly but there is a problem : 
I can enter my phishing website without any issue, but when I enter my Google username and I click on "next", the page where I am supposed to enter my password doesn't load... 
Like that : 
![image](https://user-images.githubusercontent.com/36643560/79459680-ee4c9c00-7ff3-11ea-9480-e3ed6e442364.png)
The blue line loads again and again... My VPS is located in the USA. Can someone help me ?
Thank you

**Comment by Anonymoushawk** [comment] 2020-04-16 19:24
change your subfilters like e.g.  search: 'https://{hostname}/signin/', replace: 'https://{hostname}/signin/'  it will solve your problem.

**Comment by horllste** [comment] 2020-04-16 20:14
Or try and build your own phishlet from scratch

**Comment by peaillaud** [comment] 2020-04-17 12:33
> change your subfilters like e.g. search: 'https://{hostname}/signin/', replace: 'https://{hostname}/signin/' it will solve your problem.

Where are the changes between the search and the replace ?

**Comment by Anonymoushawk** [comment] 2020-04-17 14:36
@aillaudpe replace
- {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/signin/', replace: 'https://{hostname}/signin/', mimes: ['text/html', 'application/json']}

**Comment by petr209** [comment] 2020-04-17 15:54
@Anonymoushawk that's exactly where I thought the issue was last week, I tried replacing it with various strings but never got pass that. It's either loading or it's not even going to load at all for me

**Comment by horllste** [comment] 2020-04-17 18:25
Login path... Check that

**Comment by peaillaud** [comment] 2020-04-17 18:35
> Login path... Check that

I checked Google Chrome console and it would come from a problem from a request to play.google.com (play.{hostname}.com with custom dns) but yet it should work because the hosts for the google phishlet include play.google.com... I don't get it

And sorry for my bad english

**Comment by horllste** [comment] 2020-04-17 18:41
Open Google login page in your browser and copy the url then replace with what you have in your phishlet under the login path section

**Comment by petr209** [comment] 2020-04-17 22:27
Same, I checked in burp, replaced the login with every url that was captured and yet still no luck lol. I don't know what else is there or not. The only extra url I see there is youtube check, but that shouldn't have any effect on it

**Comment by An0nUD4Y** [comment] 2020-05-03 09:37
This issue is bigger than that, Just check console for errors.
There Are Two Major Errors Occuring one with play.google.com & other with accounts-google.com.
I think the template is not making changes to domain and not passing to those actual servers correctly.
I strongly believe that one should try changing the sub filters correctly & and can also try to add new subdomains as complete hostname play.google.com.{hostaname} & similar for Accounts-google.com.{hostaname} .
One can also Try Old Google Template from PR list of Evilginx and Can try to insert the script which is used here And Just Test.

ALERT : For me Few Of the things not worked And I didn't Tried Few.

LET ME KNOW IF SOMEONE HAS MORE GOOD IDEAS AND HAVE WORKING TEMPLATE.
Contact me On Telegram :  https://t.me/its_udy


I ALSO HAVE ISSUES WITH GOOGLE INVISIBLE RECAPTCHA PROXYING. READ MY TEMP SOLUTION HERE ( https://github.com/kgretzky/evilginx2/pull/476 )

**Comment by hash3liZer** [comment] 2020-07-07 00:32
@An0nUD4Y Same thing again.

**Comment by hash3liZer** [comment] 2020-07-07 00:39
@peaillaud @horllste @petr209 @Anonymoushawk The Issue originates from the internal javascript which is used to make request on the fly while signing in. It's not related to `play.google.com`. I've fixed those console errors regarding `play.google.com`. But the actual issue is when the AJAX request is made with a different payload. The payload from the original site and from the proxied site is way too much different. The request would work fine when payload from the original request is used. So, that's where the problem is. The javascript part is highly obfuscated at the point. If you have any further solutions on this, open up a new issue.

**Closed as completed by hash3liZer** 2020-07-07 00:39 UTC

**Comment by kameni14** [comment] 2021-02-20 16:58
Please , google phishlets don't work for me.any update of that.thanks.
