### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Mematibash0** [hash3liZer/phishlets#29] opened 2021-03-28 18:38 UTC
Hello, I met you while looking at the arguments about your evilginx2. I wonder if you can help me at ?
my problem - listen tcp :443: bind: address already in use.

**Comment by isamalia** [comment] 2021-03-28 19:18
sudo systemctl stop apache2 should work, if no then sudo kill 443 sudo kill 80

**Comment by Mematibash0** [comment] 2021-03-28 19:20
> sudo systemctl stop apache2 should work, if no then sudo kill 443 sudo kill 80

Thx i go and try thx

**Comment by Mematibash0** [comment] 2021-03-29 14:54
> sudo systemctl stop apache2 çalışmalıdır, eğer hayır ise sudo kill 443 sudo kill 80
I tried but it didn't work  listen tcp :443: bind: address already in use

**Comment by isamalia** [comment] 2021-03-29 17:08
You 

> > sudo systemctl stop apache2 çalışmalıdır, eğer hayır ise sudo kill 443 sudo kill 80
> > I tried but it didn't work  listen tcp :443: bind: address already in use

You have somthing installed wich is using 443, i advice you to reinstall a fresh os on your VPS and  then sudo systemctl stop apache2  and it will work, this is the easy solution, the other solution is to investigate evry think and see what is blocking.

**Comment by Mematibash0** [comment] 2021-03-29 18:01
> You
> 
> > > sudo systemctl stop apache2 çalışmalıdır, eğer hayır ise sudo kill 443 sudo kill 80
> > > I tried but it didn't work  listen tcp :443: bind: address already in use
> 
> You have somthing installed wich is using 443, i advice you to reinstall a fresh os on your VPS and then sudo systemctl stop apache2 and it will work, this is the easy solution, the other solution is to investigate evry think and see what is blocking.

I activated 443 ports to make https.okey i go and try new site.And i use freenom and digitalocean.are these okey?

**Comment by Mematibash0** [comment] 2021-03-31 00:04
> You
> 
> > > sudo systemctl stop apache2 çalışmalıdır, eğer hayır ise sudo kill 443 sudo kill 80
> > > I tried but it didn't work  listen tcp :443: bind: address already in use
> 
> You have somthing installed wich is using 443, i advice you to reinstall a fresh os on your VPS and then sudo systemctl stop apache2 and it will work, this is the easy solution, the other solution is to investigate evry think and see what is blocking.

Hello i try i open new vps and buy new domain 
lures get-url 1 and copy link 
link dont open
What do i do?

**Comment by hash3liZer** [comment] 2023-06-22 15:18
Hello, @Mematibash0 for your first issue, i thinks it clarified that the problem is because of you have a service running on port 80, 443. Try stopping that service. 

Second, check if you have successfully generated the certificates and phishlet is enabled properly. I am closing this issue for now. Feel free to message me.

**Closed as completed by hash3liZer** 2023-06-22 15:18 UTC

**Comment by sny7er** [comment] 2023-08-12 16:37
I keep getting this when I'm nearly done .. running " phishlets enable outlook "

I have setup the A records under the domain.   I've tried this several times.  I can dig outlook.mydomain and the others successfully and I have the firewall set to allow from 0.0.0.0 any to http and https.. so letsencrypt can hit it. 

Any help ?


[17:28:01] [inf] obtaining and setting up 3 TLS certificates - please wait up to 60 seconds...
[17:28:02] [err] failed to set up TLS certificates: outlook.mydomain: obtaining certificate: [outlook.mydomain] Obtain: registering account [mailto:xxv@nmcxez.com] with server: provisioning client: performing request: Get "https://acme-v02.api.letsencrypt.org/directory": dial tcp: lookup acme-v02.api.letsencrypt.org on [::1]:53: server misbehaving
